version: '3.8'

services:
  db:
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: products_db
      MARIADB_USER: usuario_app
      MARIADB_PASSWORD: clave_app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/local/products.sql:/docker-entrypoint-initdb.d/products.sql

  app:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

volumes:
  db_data: