#Declara los servicios que se van a levantar (app y db).
#Define variables de entorno comunes.
#Define el volumen db_data para guardar los datos de la base y que no se pierdan al reiniciar el contenedor.

services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=myapp_db
      - DB_USER=root
      - DB_PASS=password
  db:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: